#!/bin/bash
#  generate both inclusive and dimuon samples in parallel

# print each argument on its own line with the first line
# prefixed with "ERROR: ".
error() {
  printf >&2 "\033[1;31mERROR: \033[0m\033[31m%s\n" "$1"
  shift
  while [ "$#" -gt "0" ]; do
    printf >&2 "       %s\n" "$1"
    shift
  done
  printf >&2 "\033[0m"
}
info() {
  printf "\033[32;1m INFO: \033[0m\033[32m%s\n" "$1"
  shift
  while [ "$#" -gt "0" ]; do
    printf '       %s\n' "$1"
    shift
  done
  printf "\033[0m"
}

usage() {
  cat <<HELP

  Generate inclusive and dimuon samples for varying tungsten target depths.

 USAGE
  ./app/gen-samples [-h|--help] [-o|--out-dir DIR] DEPTH0 [DEPTH1 ...]

 OPTIONS
  -h, --help    : print this help and exit
  -o, --out-dir : write all generated data and log files to DIR

 ARGUMENTS
  DEPTH : one or more target depths in units of radiation length

HELP
}

if [ "$#" -eq 0 ]; then
  usage
  error "Need to define at least one depth."
  exit 1
fi

outdir="$PWD"
depths=""
while [ "$#" -gt 0 ]
do
  case $1 in
    --out-dir|-o)
      outdir="$2"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    -*)
      error "Unrecognized option $1"
      exit 1
      ;;
    *)
      depths="${depths} $1"
      ;;
  esac
  shift
done

if [ ! -d ${outdir} ]; then
  info "Need to create output directory '${outdir}'"
  if ! mkdir ${outdir}; then
    error "Unable to create output directory '${outdir}'."
    exit 1
  fi
fi

for depth_X0 in ${depths}
do
  info "Simulating target depth ${depth_X0}X0"
  depth_mm="$(python3 -c "print(${depth_X0}*3.50259)")"
  ./build/dimuon-simulate\
    --depth ${depth_mm} \
    10000 ${outdir}/inclusive_${depth_X0}.root &> ${outdir}/inclusive_${depth_X0}.log &
  ./build/dimuon-simulate \
    --depth ${depth_mm} \
    --bias 1e4 \
    --filter 1000 \
    1000000 ${outdir}/dimuon_${depth_X0}.root &> ${outdir}/dimuon_${depth_X0}.log &
done
info "Waiting for job completion..."
wait
info "done"
